### usage:
## ansible-playbook playbook.yml -i hosts

## edit hosts file before running playbook and update it with your router ip address


---
- name: Streaming Telemetry Playbook (network_cli)
  hosts: routers
  vars:
    ansible_network_os: ios
    ansible_user: cisco 
    ansible_password: cisco 
    ansible_connection: network_cli
    xpaths:
      1: '/process-cpu-ios-xe-oper:cpu-usage/cpu-utilization/five-seconds'
      2: '/memory-ios-xe-oper:memory-statistics/memory-statistic'
    receiver_ip: '192.168.54.1'
    period: 500
    receiver_port: 57500 
  gather_facts: false

  tasks:
    - name: Configure streaming telemetry
      cisco.ios.ios_config:
        lines:
          - encoding encode-kvgpb
          - filter xpath {{item.value}}
          - stream yang-push
          - update-policy periodic {{period}}
          - receiver ip address {{receiver_ip}} {{receiver_port}} protocol grpc-tcp
        parents: telemetry ietf subscription {{item.key}}
      loop: "{{ lookup('dict',xpaths) }}"
  